// Personality-driven dialogue. Each voice maps a situation key to candidate lines.
// Placeholders: {target} {task} {manager} {report} {boss} {score} {bonus}
// Missing keys fall back to the `generic` voice.

const DIALOGUE = {
  generic: {
    morning: ["Morning, everyone.", "Okay. New day."],
    taskStart: ["Starting on {task}.", "On to {task}."],
    taskDone: ["Finished {task}.", "Done with {task}."],
    stressHigh: ["This is a lot right now.", "I need a minute."],
    meltdown: ["I can't. I just can't right now. Stepping away."],
    relaxed: ["Feeling pretty good today."],
    break: ["Grabbing a coffee.", "Quick break."],
    lunch: ["Lunch time.", "Finally, food."],
    smallTalk: ["Hey {target}, how's it going?", "{target}, did you see the email from facilities?"],
    replyWarm: ["Not bad, thanks for asking!", "Ha, yeah. Hanging in there."],
    replyCold: ["Fine.", "Mm-hm."],
    replyStressed: ["Can't talk, sorry.", "Not now, please."],
    eventBad: ["Great. Just great.", "Of course that happens today."],
    eventGood: ["Oh nice!", "Well, that's something."],
    rewarded: ["Thank you, really.", "Appreciate it."],
    praised: ["Thanks.", "Good to hear."],
    neutral: ["Okay, noted."],
    punished: ["Understood. I'll do better."],
    warned: ["A formal warning... okay."],
    fired: ["...Right. I'll get my things."],
    coworkerFired: ["Wow. That's rough.", "I can't believe it."],
    newHire: ["Welcome aboard, {target}!"],
    bossNearby: ["*straightens up*"],
    endOfDay: ["See everyone tomorrow.", "Logging off."],
    rework: ["Fixing it now."],
    userGreet: ["Hi there!"],
    userPraise: ["Oh, thank you!"],
    userCriticize: ["...Okay. Noted."],
    userHowGood: ["Doing alright, thanks!"],
    userHowBad: ["Honestly? Stressed."],
    userGeneric: ["Sure, I'll keep that in mind.", "Hm, interesting."],
    sickCall: ["Calling in sick today, sorry everyone."],
    assign: ["{target}, please {task}."],
    catchError: ["{target}, there's a mistake in your work on {task}. Please fix it."],
    approve: ["Looks good, {target}."],
  },

  eager: {
    morning: ["Good morning everyone!! ☀️ Ready to crush it today!", "Morning! I brought snacks, they're by the printer 🍪", "Hi all! I made a to-do list for my to-do list 😄"],
    taskAssigned: ["On it, {manager}! 💪", "Absolutely, I'll get right on that!", "You got it! Should I CC you when it's done?"],
    taskStart: ["Starting {task} now!", "Okay, {task}. Let's gooo.", "Diving into {task} 🏊"],
    taskDone: ["{task} is done! Sent it over to {manager} 🎉", "Finished {task}! What's next?", "{task}: ✅"],
    rework: ["Oh no, sorry {manager}! Fixing it right away 😣", "Ugh, I should have caught that. Redoing it now!", "Sorry!! Won't happen again, I promise."],
    stressHigh: ["I'm fine! Totally fine! Everything's fine 🙂🙂🙂", "Is it normal to have this many tabs open?", "I think I'm falling behind... I'll just skip lunch."],
    meltdown: ["Sorry, I need to step out for a minute... 😢", "I just... I'm trying so hard and it's not enough. Be right back."],
    relaxed: ["Honestly I love this job 😊", "Ooh, I'm in the zone today!"],
    break: ["Quick water break, back in 5!", "Gonna stretch my legs real quick 🚶", "Coffee run! Anyone want anything?"],
    lunch: ["Lunch! Anyone want to eat together? 🥪", "I packed leftovers, it's pasta day!"],
    smallTalk: ["{target}! Did you watch the game last night?", "Hey {target}, any tips for surviving month-end? 😅", "{target}, I tried that café you recommended, SO good!", "{target}, how was your weekend?"],
    replyWarm: ["Haha yes!! Totally agree 😄", "Aww thanks {target}! You're the best.", "Omg same."],
    replyCold: ["Oh! Um, okay, sorry to bother you.", "Haha... right. Yeah."],
    replyStressed: ["Sorry {target}, I'm drowning a bit 😅 later?", "Can't talk, trying to finish this!"],
    eventBad: ["Oh no... okay, we can handle this!", "Silver lining: character building? 😅"],
    eventGood: ["YAY 🎉", "Best day ever!!", "This office is the best 🥹"],
    rewarded: ["Wait, really?! Thank you so much, Victoria!! 🥹", "I'm going to frame this review. Thank you!", "This means so much. I won't let you down!"],
    praised: ["Thank you! I'll keep it up!", "Yesss 😊 thank you!"],
    neutral: ["Okay! I'll aim higher next time 💪", "Got it, room to grow!"],
    punished: ["I'm so sorry... I'll stay late and fix it.", "I really thought I was doing well 😞", "I'll do better. I promise."],
    warned: ["A formal warning?? I... okay. I'll fix this. 😟", "I can't lose this job. I'll work harder."],
    fired: ["I... understand. Thank you for the opportunity. 😢", "Okay. Can I at least take the plant?"],
    coworkerFired: ["Wait, {target} is GONE? 😨", "That's terrifying. Am I next?", "Poor {target}... I'm going to miss them."],
    newHire: ["Welcome {target}!!! I'll show you where the good snacks are 🍪", "Hi {target}! So excited you're here!"],
    bossNearby: ["*types faster*", "Hi Victoria! 👋 ...she didn't wave back.", "*pretends to read a very important spreadsheet*"],
    endOfDay: ["Great day team! See you tomorrow 👋", "Bye everyone! Same time tomorrow!"],
    userGreet: ["Hi!! 👋 Welcome to the office!", "Oh hi! Are you the new consultant? Nice to meet you!"],
    userPraise: ["Aww, thank you!! That made my day 🥹", "Really?! Thank you so much!"],
    userCriticize: ["Oh... sorry. I'll try harder. 😞", "That's fair, I guess. I'll work on it."],
    userHowGood: ["Great! A little busy but I love it 😊", "Super good! I'm learning so much."],
    userHowBad: ["Honestly? Kind of overwhelmed 😅 but I'll manage!", "I'm okay! ...Mostly. Ask me after the report."],
    userGeneric: ["Ooh, good point!", "Haha, totally!", "I'll write that down! 📝"],
    sickCall: ["So sorry everyone, I'm sick today 🤒 I'll check email from bed!"],
  },

  sarcastic: {
    morning: ["Morning. Allegedly.", "I'm here. Physically.", "Good morning to everyone except the printer."],
    taskAssigned: ["Oh good, more work. My favorite.", "Yep. Sure. Adding it to the pile, {manager}.", "Can't wait. Truly."],
    taskStart: ["Starting {task}. Pray for me.", "{task}. Living the dream.", "Okay {task}, it's you and me."],
    taskDone: ["{task} is done. Applause optional.", "Finished {task}. Nobody panic.", "{task}: handled. I accept payment in coffee."],
    rework: ["Cool. Cool cool cool. Fixing it.", "Sure, {manager}, I'll fix the one comma.", "Redoing it. Again. Fun."],
    stressHigh: ["My heart rate is a spreadsheet and it's going up.", "If anyone needs me I'll be quietly screaming.", "I've started talking to my monitor. It doesn't answer, which is fair."],
    meltdown: ["Nope. Nope nope nope. I'm going outside.", "I'm going to go stare at a wall for ten minutes. Don't follow me."],
    relaxed: ["Weirdly, I don't hate today.", "Is this what calm feels like? Suspicious."],
    break: ["Coffee. Now. Don't talk to me.", "Going to go refill my cold brew. Third one. Don't judge.", "Taking a 'strategic hydration break'."],
    lunch: ["Lunch. The only meeting I enjoy.", "Eating at my desk like a raccoon."],
    smallTalk: ["{target}, rate today out of ten. I'll go first: three.", "{target}, if I fake a fire drill, will you back me up?", "{target}, the vending machine ate my dollar. Again.", "{target}, did you also get the 'per my last email' email?"],
    replyWarm: ["Ha. Fair.", "Okay that actually made me laugh.", "You're one of the good ones, {target}."],
    replyCold: ["Riveting.", "Wow. Okay.", "Sure, {target}."],
    replyStressed: ["Not now, I'm one email away from moving to the woods.", "Can it wait until I've stopped vibrating?"],
    eventBad: ["Love that for us.", "Ah yes, the universe's daily prank.", "This is fine. 🔥"],
    eventGood: ["Okay, I'll allow it.", "Free food is my love language.", "Finally, a plot twist I enjoy."],
    rewarded: ["Wait. Me? Are you sure you read the right name?", "A bonus? I'm genuinely speechless. Briefly.", "Okay, I'll admit it. That feels nice."],
    praised: ["Huh. Thanks.", "Noted. Saving this for my eulogy."],
    neutral: ["Middle of the pack. My natural habitat.", "'Meets expectations.' Story of my life."],
    punished: ["Great. Love that for me.", "Cool, I'll just add that to my collection of anxieties.", "Message received. Loudly."],
    warned: ["A formal warning. Lovely. Framing it next to my student loans.", "Okay, now I'm actually worried."],
    fired: ["Well. At least I don't have to fix the printer anymore.", "Fired. Honestly? Called it."],
    coworkerFired: ["They fired {target}?? This place is a horror movie.", "Rest in peace, {target}'s parking spot.", "Welp. Updating my résumé 'just because'."],
    newHire: ["Welcome, {target}. Run while you can. Kidding. Mostly.", "Hi {target}. The coffee is bad and so are the chairs."],
    bossNearby: ["*minimizes 14 tabs*", "*sudden intense typing*", "Hi Victoria. Yes, this is a spreadsheet. A real one."],
    endOfDay: ["And I'm free. Goodbye.", "Logging off before anyone can 'quickly' ask me something."],
    userGreet: ["Oh. A visitor. Hi.", "Hey. Don't sit in that chair, it squeaks."],
    userPraise: ["...Thanks. That's weirdly nice.", "Okay, now I'm suspicious. But thanks."],
    userCriticize: ["Wow. Get in line.", "Thanks, I'll add that to the list of things I'm worried about."],
    userHowGood: ["Surprisingly okay. Don't jinx it.", "Not bad. Caffeinated."],
    userHowBad: ["On a scale of one to ten? Printer jam.", "Stressed. Over-caffeinated. Thriving, technically."],
    userGeneric: ["Bold take.", "Mm. Sure.", "That's one way to look at it."],
    sickCall: ["Sick today. Real sick. Not 'Monday' sick. Bye."],
  },

  strict: {
    morning: ["Good morning. Agenda is in your inbox.", "Morning. Let's hit our targets today, people.", "Good morning. Desks clear, priorities set."],
    assign: ["{target}, please {task}. I'd like it by end of the hour.", "{target}: {task}. Follow the template.", "{target}, next on your list: {task}. No shortcuts."],
    taskStart: ["Working on {task}. Do not disturb unless urgent.", "Starting {task}."],
    taskDone: ["{task} complete. Filed in the correct folder.", "Finished {task}. On schedule."],
    catchError: ["{target}, your work on {task} has errors. Redo it, carefully this time.", "{target}, I found mistakes in {task}. Please read the guidelines again.", "This isn't acceptable, {target}. {task} needs to be fixed."],
    approve: ["{task} approved. Good work, {target}.", "Fine work on {task}, {target}.", "Approved."],
    stressHigh: ["Why is nothing ever done right the first time?", "I have eleven things due and zero minutes.", "I'm going to need everyone to focus. Including me."],
    meltdown: ["I need five minutes. Nobody touch my planner.", "I can't hold this whole office together alone. Back shortly."],
    relaxed: ["Everything is on schedule. I could get used to this.", "Inbox zero. A rare and beautiful thing."],
    break: ["Taking my scheduled ten-minute break.", "Getting tea. Back in exactly ten."],
    lunch: ["Lunch. Thirty minutes, then back to it.", "Working lunch for me, as usual."],
    smallTalk: ["{target}, are your timesheets submitted?", "{target}, did you read the updated policy memo?", "{target}, I reorganized the supply closet. You're welcome."],
    replyWarm: ["That's... actually helpful, {target}. Thanks.", "Agreed. Good point."],
    replyCold: ["Let's keep it professional, {target}.", "Is this work-related?", "Mm. Back to work, please."],
    replyStressed: ["Not now, {target}.", "Unless it's on fire, it can wait."],
    eventBad: ["This is exactly why we need contingency plans.", "Unbelievable. Adjusting the schedule."],
    eventGood: ["Fine. Five minutes, everyone.", "Well. That's pleasant, I suppose."],
    rewarded: ["Thank you. The planning paid off.", "Appreciated. I'll keep standards high."],
    praised: ["Thank you. As expected.", "Good. Noted."],
    neutral: ["Acceptable isn't excellent. I'll tighten things up.", "Understood. Room for improvement."],
    punished: ["That's... not fair, but I'll fix it.", "I'll be implementing stricter checks immediately.", "Understood. It won't happen again."],
    warned: ["A warning. On my record. I've never... understood.", "I'll fix this. Whatever it takes."],
    fired: ["I gave this branch everything. Fine.", "I'll have my transition notes on your desk in an hour."],
    coworkerFired: ["Losing {target} will hurt our throughput.", "That's... a significant change. I'll adjust the org chart."],
    newHire: ["Welcome, {target}. Onboarding packet is on your desk. Read all of it.", "{target}, welcome. Questions go through me."],
    bossNearby: ["Victoria. Everything is on track.", "*adjusts planner to look busier*"],
    endOfDay: ["Good work today. Tomorrow's agenda is posted.", "Logging off. Remember timesheets."],
    userGreet: ["Hello. Do you have an appointment?", "Good day. Please sign the visitor log."],
    userPraise: ["Thank you. It's all in the planning.", "I appreciate that. Someone notices."],
    userCriticize: ["I'll take that under consideration. Formally.", "Feedback noted. I disagree, but noted."],
    userHowGood: ["On schedule. That's all I ask for.", "Productive. Thank you for asking."],
    userHowBad: ["Overloaded. Nobody follows the process.", "Stressed. If one more thing goes wrong today..."],
    userGeneric: ["Please submit that in writing.", "Let's put that on the agenda.", "Interesting. Not a priority."],
    sickCall: ["I'm out sick. I've delegated everything. Do NOT touch my planner."],
  },

  laidback: {
    morning: ["Mornin' team! 😎 Let's have a good one.", "Hey hey! Who wants coffee? I'm buying.", "Morning! Remember: we're a team, not a factory."],
    assign: ["Hey {target}, could you {task} when you get a sec? No rush. Well, little rush.", "{target}, my friend! Mind taking care of {task}?", "{target}, got one for you: {task}. You'll nail it."],
    taskStart: ["Alright, let's knock out {task}.", "Time for {task}. Somebody put on some music."],
    taskDone: ["Boom, {task} done 👊", "{task} — handled. Not bad, Marcus."],
    catchError: ["Hey {target}, small thing, {task} has a couple of mistakes. Mind taking another pass?", "{target}, no stress, but {task} needs a fix or two."],
    approve: ["{task} looks great, {target}! 🙌", "Nice job on {task}, {target}!", "Ship it! 🚢"],
    stressHigh: ["Okay, things are getting a little spicy 🌶️", "Deep breaths, Marcus. Deep breaths.", "Why are there so many emails today?"],
    meltdown: ["I need to go walk around the block, folks. Back soon.", "Even I have limits, apparently. Taking five."],
    relaxed: ["Vibes in the office are immaculate today ✨", "Good day to be a team lead."],
    break: ["Ping-pong break, anyone? 🏓", "Gonna grab a coffee, holler if you need me.", "Stepping out for some fresh air."],
    lunch: ["Taco Tuesday energy! Who's in? 🌮", "Lunch on the patio, anyone?"],
    smallTalk: ["{target}! How's life? Really, how is it?", "{target}, I'm thinking of starting a fantasy league for the office.", "{target}, you doing okay? You look like you need a coffee.", "{target}, best sandwich place nearby: go."],
    replyWarm: ["Haha, love it {target}!", "You're the best, {target} 🙌", "That's what I'm talking about!"],
    replyCold: ["Ha, okay, okay.", "Fair enough, {target}."],
    replyStressed: ["Gimme ten, {target}, I'm putting out a fire 🔥", "Can we circle back? Swamped."],
    eventBad: ["Eh, could be worse. Probably.", "Alright team, we roll with it."],
    eventGood: ["Now THAT's a morale boost 🎉", "Treat yo' self, everyone!", "This is the content I'm here for."],
    rewarded: ["Ayy! Thanks Victoria! Drinks on me, team 🍻", "Appreciate it! The team did the heavy lifting."],
    praised: ["Thanks! It's all the team.", "Hey, I'll take it 😎"],
    neutral: ["Middle of the road. I'll take it.", "Could be better, could be worse!"],
    punished: ["Oof. Fair. I'll tighten things up.", "Okay, message received. Time to get serious-ish.", "Yikes. Alright, I hear you."],
    warned: ["Formal warning, huh. Okay... maybe I need to actually read the reports.", "That stings. I'll step it up."],
    fired: ["Well, it's been a ride. Love you all. Stay chill. ✌️", "No hard feelings. Mostly."],
    coworkerFired: ["Man... {target} was good people.", "That's rough. Let's take care of each other, team.", "Gonna miss {target}. Seriously."],
    newHire: ["Welcome to the fam, {target}! 🙌", "{target}! Glad you're here. Lunch is on me today."],
    bossNearby: ["Hey Victoria! Looking sharp.", "*hides the ping-pong paddle*"],
    endOfDay: ["Great hustle today, team. Go home, rest up!", "Peace out, everybody ✌️"],
    userGreet: ["Hey hey! Welcome! Grab a chair.", "Yo! New face! What's up?"],
    userPraise: ["Appreciate you! 🙌", "That's what's up. Thanks!"],
    userCriticize: ["Fair, fair. I'll work on it.", "Oof. Okay, I hear you."],
    userHowGood: ["Living the dream! 😎", "Pretty great, honestly."],
    userHowBad: ["Bit swamped, not gonna lie.", "I've been better. Ask me after a coffee."],
    userGeneric: ["Love that energy.", "Ha! Good one.", "Let's circle back on that 😄"],
    sickCall: ["Out sick today, team. You got this. ✌️🤒"],
  },

  boss: {
    morning: ["Good morning. Reports at noon and five. Make them count.", "Morning. Headquarters is watching our numbers this week.", "Morning. I expect results today."],
    taskStart: ["I'll be in my office. {task}.", "Busy with {task}. Do not interrupt me unless it's important."],
    taskDone: ["Done. Next.", "Finished. Now let's see what the rest of you have."],
    stressHigh: ["Headquarters is breathing down my neck. Don't make it worse.", "Somebody explain to me why these numbers look like this.", "I need this branch performing. Now."],
    meltdown: ["Everyone. Back. To. Work. I'm going to my office.", "I'm taking a call. With nobody. Just give me ten minutes."],
    relaxed: ["The numbers look good. Don't get comfortable.", "Decent day. Keep it going."],
    break: ["Getting an espresso.", "Five minutes. Don't burn the building down."],
    lunch: ["Lunch meeting with the regional VP.", "I'll be at lunch. Keep your phones on."],
    smallTalk: ["{target}. How's that workload?", "{target}, what's your status?", "{target}, walk me through your day."],
    replyWarm: ["Good. Keep it up, {target}.", "Fine. Carry on."],
    replyCold: ["I don't need excuses, {target}.", "Less talking, more doing.", "Mm."],
    replyStressed: ["Not now.", "Put it in an email."],
    eventBad: ["Fix it. Now.", "This is costing us money."],
    eventGood: ["Fine. Enjoy it. Quickly.", "A small treat. Don't make it a habit."],
    checkIn: ["{target}. What are you working on?", "{target}, is that spreadsheet or solitaire?", "Just observing. Pretend I'm not here.", "{target}, show me your progress."],
    assignUrgent: ["{target}, drop what you're doing. I need you to {task}. Today.", "{target}, urgent: {task}. Headquarters is waiting."],
    reportIntro: ["Progress report time. Let's see who earned their paycheck.", "Report time. I've reviewed everyone's output.", "Alright. Numbers are in."],
    reportOutro: ["That's all. Back to work.", "Do better than this next time. Dismissed.", "Good work where it was good. Fix the rest."],
    bossPraise: ["{target}, outstanding work. Bonus approved: ${bonus}.", "{target}. That's what I want to see. ${bonus} bonus.", "Excellent, {target}. Don't let it go to your head. ${bonus} bonus."],
    bossGood: ["{target}, solid. Keep it up.", "Good work, {target}."],
    bossNeutral: ["{target}, acceptable. Barely.", "{target}, average. I don't pay for average forever."],
    bossScold: ["{target}, that score is not good enough.", "{target}, I expected more. Step it up.", "{target}, see me after. This is disappointing."],
    bossWarn: ["{target}, this is a formal warning. Three strikes and you're out.", "{target}, unacceptable. I'm putting this in your file.", "{target}. Formal warning. Don't make me write another one."],
    firing: ["{target}, pack your desk. You're done here.", "{target}, I've given you enough chances. You're terminated, effective immediately.", "{target}. HR will see you out."],
    endOfDay: ["Done for today. Be on time tomorrow.", "Go home. Come back sharper."],
    userGreet: ["And you are?", "Who let you in? ...Fine. Welcome."],
    userPraise: ["I know.", "Flattery won't get you a desk here. But thank you."],
    userCriticize: ["Bold of you. Noted.", "I'll remember you said that."],
    userHowGood: ["Productive. The numbers look good.", "Busy. As always."],
    userHowBad: ["Headquarters is on my back. That's how I am.", "Stressed. My team needs to step up."],
    userGeneric: ["Is there a point?", "Send me a memo.", "Interesting. I'll consider it."],
    newHire: ["{target}. You start now. Don't disappoint me."],
    coworkerFired: ["It had to be done."],
  },

  stoic: {
    morning: ["Morning.", "Here.", "Good morning."],
    taskAssigned: ["Okay.", "Will do, {manager}.", "Understood."],
    taskStart: ["Starting {task}.", "{task}. On it."],
    taskDone: ["{task} done.", "Finished {task}."],
    rework: ["Fixing it.", "Understood. Correcting."],
    stressHigh: ["...This is a lot.", "Need to focus."],
    meltdown: ["Taking a walk.", "Need some air."],
    relaxed: ["Good day.", "Calm."],
    break: ["Break.", "Water."],
    lunch: ["Lunch.", "Eating."],
    smallTalk: ["{target}. Doing okay?", "{target}, need a hand with anything?"],
    replyWarm: ["Thanks, {target}.", "Appreciate it."],
    replyCold: ["Okay.", "Mm."],
    replyStressed: ["Later.", "Busy."],
    eventBad: ["Hm.", "Unfortunate."],
    eventGood: ["Nice.", "Good."],
    rewarded: ["Thank you.", "Appreciated. Thank you."],
    praised: ["Thanks."],
    neutral: ["Okay."],
    punished: ["Understood.", "I'll improve."],
    warned: ["Understood. Won't happen again."],
    fired: ["Okay. Goodbye, everyone."],
    coworkerFired: ["Hm. Sorry to see {target} go."],
    newHire: ["Welcome, {target}."],
    bossNearby: ["*keeps working*"],
    endOfDay: ["Night.", "Goodnight, everyone."],
    userGreet: ["Hello."],
    userPraise: ["Thanks."],
    userCriticize: ["Noted."],
    userHowGood: ["Fine."],
    userHowBad: ["Stressed, honestly."],
    userGeneric: ["Okay.", "Hm."],
  },

  climber: {
    morning: ["Good morning, team! Let's leverage today 🚀", "Morning! Big opportunities today.", "Rise and grind, everyone."],
    assign: ["{target}, I'd love for you to take this one on: {task}. Great visibility!", "{target}, quick win for you: {task}.", "{target}, can you {task} ASAP? Let's action it."],
    taskStart: ["Driving {task} forward.", "Taking ownership of {task}."],
    taskDone: ["{task}: delivered. Updating my LinkedIn.", "Closed out {task}. Momentum!"],
    catchError: ["{target}, {task} isn't client-ready. Let's iterate.", "{target}, a few gaps in {task}. Circle back and fix?"],
    approve: ["{task} — great execution, {target}!", "Love it, {target}. Shipping {task}."],
    stressHigh: ["Bandwidth is... limited right now.", "We need to realign priorities. Fast."],
    meltdown: ["I need to step out and recalibrate.", "Taking ten to re-center."],
    relaxed: ["Crushing our KPIs today 📈", "Great alignment across the team."],
    break: ["Quick coffee chat with myself ☕", "Recharging. Back in five."],
    lunch: ["Networking lunch!", "Lunch-and-learn time."],
    smallTalk: ["{target}, what are your five-year goals?", "{target}, have you read the new leadership book? Life-changing.", "{target}, let's grab a coffee and sync."],
    replyWarm: ["Love that, {target}!", "Great insight!"],
    replyCold: ["Let's take that offline.", "Okay, parking that."],
    replyStressed: ["Can we sync later?", "No bandwidth right now."],
    eventBad: ["Challenges are just opportunities in disguise.", "We'll pivot."],
    eventGood: ["Culture win! 🎉", "Love a team moment."],
    rewarded: ["Thank you, Victoria! Ready for the next challenge.", "Appreciate the recognition!"],
    praised: ["Thanks! On to the next win."],
    neutral: ["Solid baseline to grow from."],
    punished: ["Understood. I'll course-correct.", "Feedback is a gift. A painful one."],
    warned: ["A warning. Okay. Time to over-deliver."],
    fired: ["I'll... update my LinkedIn. 'Open to work.'"],
    coworkerFired: ["Wow. Big change for the org."],
    newHire: ["Welcome, {target}! Let's connect on LinkedIn."],
    bossNearby: ["Victoria! Love what you're doing with the strategy."],
    endOfDay: ["Productive day! Logging off to journal.", "Great hustle, all."],
    userGreet: ["Hi! Great to connect!"],
    userPraise: ["Thanks! Mind leaving that as an endorsement?"],
    userCriticize: ["Feedback is a gift. Thank you."],
    userHowGood: ["Thriving!"],
    userHowBad: ["Stretched thin, honestly."],
    userGeneric: ["Let's take that offline.", "Great synergy there."],
  },
};
